// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBfmG09eGkWItRLS-SIMQZxr_i5_2GugYY',
    appId: '1:848602017569:web:86d143f795d7911387d860',
    messagingSenderId: '848602017569',
    projectId: 'spotify-b2183',
    authDomain: 'spotify-b2183.firebaseapp.com',
    storageBucket: 'spotify-b2183.appspot.com',
    measurementId: 'G-ZZF7M6MSX8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7WEBUBlLuhSEaImY7oZZzunIaTEHd9GM',
    appId: '1:848602017569:android:fcccb87269bdc28887d860',
    messagingSenderId: '848602017569',
    projectId: 'spotify-b2183',
    storageBucket: 'spotify-b2183.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAco3N7vnPknsBCao2_A_xwl5Cp_THSOIQ',
    appId: '1:848602017569:ios:ded4f98321fe1fa187d860',
    messagingSenderId: '848602017569',
    projectId: 'spotify-b2183',
    storageBucket: 'spotify-b2183.appspot.com',
    iosClientId: '848602017569-qlmj0uidrgbinpg3kp7166ckse05qlr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.popapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAco3N7vnPknsBCao2_A_xwl5Cp_THSOIQ',
    appId: '1:848602017569:ios:ded4f98321fe1fa187d860',
    messagingSenderId: '848602017569',
    projectId: 'spotify-b2183',
    storageBucket: 'spotify-b2183.appspot.com',
    iosClientId: '848602017569-qlmj0uidrgbinpg3kp7166ckse05qlr1.apps.googleusercontent.com',
    iosBundleId: 'com.example.popapp',
  );
}
